### ISSUE TITLE
OrbitControls Stickiness

### ISSUE THREAD

**Issue by mysterybear** [pmndrs/three-stdlib#101]
Please see https://github.com/pmndrs/drei/issues/638

**Comment by drcmda** [comment]
@mysterybear you or someone else needs to update three-stdlib. you can just cherry-pick their commits. we do no use three/jsm because we need to be able to apply bugfixes that three doesnt allow, but the downside is that we might miss upstream fixes.

**Comment by bjornstar** [comment]
This was fixed in version 2.5.11
