### ISSUE TITLE
GLTFExporter empy export

### ISSUE THREAD

**Issue by mordv** [pmndrs/three-stdlib#103]
- `three` version: 0.134.0
- `three-stdlib` version: 2.5.10

### Problem description:

GLTFExporter from `three-stdlib` results in empty export.

### Relevant code:

https://codesandbox.io/s/exporter-9zlzn?file=/src/index.js:575-703

**Comment by AndreiCBogdan** [comment]
Any updates on this? Currently experiencing the same problem

**Comment by mysterybear** [comment]
Same. Guess I'll try the one from the Three.js directory and see if that works.

**Comment by mysterybear** [comment]
Yep this one works https://github.com/mrdoob/three.js/blob/master/examples/jsm/exporters/GLTFExporter.js

**Comment by drcmda** [comment]
@mysterybear could you update/pr ?

**Comment by mysterybear** [comment]
@drcmda yeah I'll try today

**Comment by mysterybear** [comment]
Hi @drcmda I've put a draft up here https://github.com/pmndrs/three-stdlib/pull/167 it's not ready yet, I'm just blocked on some things, I've written in the comments/conversation, cheers!
