### ISSUE TITLE
[TS2] Loaders

### ISSUE THREAD

**Issue by joshuaellis** [pmndrs/three-stdlib#11]
### Suggested implementation:

- [ ] low/IFFParser
- [ ] lwo/LWO2Parser
- [ ] lwo/LWO3Parser
- [ ] 3DMLoader
- [ ] 3MFLoader
- [ ] AMFLoader
- [ ] AssimpLoader
- [ ] BasisTextureLoader
- [ ] BVHLoader
- [ ] ColladaLoader
- [ ] DDSLoader
- [ ] DRACOLoader
- [ ] EXRLoader
- [ ] FBXLoader
- [ ] GCodeLoader
- [ ] GLTFLoader
- [ ] HRDCubeTextureLoader
- [ ] KMZLoader
- [ ] LDrawLoader
- [ ] LottieLoader
- [ ] LUT3dlLoader
- [ ] LUTCubeLoader
- [ ] LWOLoader
- [ ] MD2Loader
- [ ] MDDLoader
- [ ] MMDLoader
- [ ] MTLLoader
- [ ] NodeMaterialLoader
- [ ] NRRDLoader
- [ ] OBJLoader
- [ ] PCDLoader
- [ ] PDBLoader
- [ ] PLYLoader
- [ ] PRWMLoader
- [ ] PVRLoader
- [ ] RGBELoader
- [ ] RGBMLoader
- [ ] STLLoader
- [ ] SVGLoader
- [ ] RDSLoader
- [ ] TGALoader
- [ ] TiltLoader
- [ ] TTFLoader
- [ ] VOXLoader
- [ ] VRMLoader
- [ ] VTKLoader
- [ ] XLoader
- [ ] XYZLoader

**Comment by alexzaganelli** [comment]
Can I suggest also:

* [ ]  FontLoader

Thanks a lot

**Comment by joshuaellis** [comment]
Hi @alexzaganelli, `FontLoader` is part of the `three` library if I'm right? So we won't be able to change the source file for that into TS. However, these files do have TS versions – `@types/three` located in the repo [`three-ts-types`](https://github.com/three-types/three-ts-types).

**Comment by alexzaganelli** [comment]
Thank you @joshuaellis 

BTW right now is not possibile to use `useLoader(FontLoader, font)` without getting `Proto is not a constructor` error in _react-three-next_.

Do you have some suggestion?
Thank you in advance

**Comment by joshuaellis** [comment]
@alexzaganelli for this question you should look at asking in `react-three-next` or the discord server - https://discord.gg/poimandres

**Comment by MDransfeld** [comment]
@joshuaellis `FontLoader` has been moved to `examples/jsm/loaders/FontLoader.js` in `three` 0.133. Should this now be imcluded in `three-stdlib`?

**Comment by joshuaellis** [comment]
> @joshuaellis `FontLoader` has been moved to `examples/jsm/loaders/FontLoader.js` in `three` 0.133. Should this now be imcluded in `three-stdlib`?

Yes, probably, if you want to make a PR that would be fantastic.
