### ISSUE TITLE
Attempted import error: 'FramebufferTexture' is not exported from 'three'

### ISSUE THREAD

**Issue by leminhtuanlc92** [pmndrs/three-stdlib#123]
- `three` version: 0.134.0
- `three-stdlib` version: 2.8.2

![a1](https://user-images.githubusercontent.com/34678201/151481918-f7e64716-300e-432e-9299-c53df60d89c0.png)

In Lensflare.js, there are import of FramebufferTexture
![a2](https://user-images.githubusercontent.com/34678201/151481937-d5a34a49-82c5-49f2-880a-e47765b418fc.png)

but in type check of three, no FramebufferTexture at all
![a3](https://user-images.githubusercontent.com/34678201/151481956-79fcd535-1635-4bb6-a04b-0808c45fbddb.png)

**Comment by 0xm0** [comment]
I got the same issue for a while now, realized I've been using node `16.13.0` & npm `7.23.0`

Upgraded using nvm to node `16.13.1` & npm `8.1.2` and it worked first try.

For anyone else who had the same issue.
