### ISSUE TITLE
FramebufferTexture' is not exported from 'three'.

### ISSUE THREAD

**Issue by wyhinton** [pmndrs/three-stdlib#132]
- "^0.134.0",
- "@types/three": "^0.134.0",
-   "three-stdlib": "^2.8.4",

OS: MacOs BigSur M1 Chip  
### Problem description

running yarn build results in:
```
./node_modules/three-stdlib/objects/Lensflare.jsAttempted import error: 'FramebufferTexture' is not exported from 'three'.
```

**Comment by bjornstar** [comment]
this should be fixed in v2.8.5
