### ISSUE TITLE
🔮 V1 Release

### ISSUE THREAD

**Issue by joshuaellis** [pmndrs/three-stdlib#14]
What do we want to achieve & have done for the v1 release?

For me, it's the TS1 implementation & a better readme 😉

**Comment by DylanTackoor** [comment]
would a storybook or some other preview script make sense? would be nice to be able to preview examples when working on them

**Comment by giulioz** [comment]
Absolutely, we could even copy the original three.js ones

**Comment by joshuaellis** [comment]
> Absolutely, we could even copy the original three.js ones

I think storybook might make the most sense (even though there are some issues with it), although I'm not sure if codesandbox could be a more powerful solution... @gsimone any thoughts?

**Comment by drcmda** [comment]
most important for me are just modules, class converts, maybe types. readme, yes i guess, but also wouldn't know how. with cannon-es we have a similar one, but if anyone wants to make it nicer, that's welcome.

storybook would be a herculean task. these are like 380 classes. we have 3-4 four people that contributed, i don't think it's doable unless this repo propagates and gets successful in that many, many people are using it.

**Comment by joshuaellis** [comment]
> storybook would be a herculean task. these are like 380 classes. unless we really dig in and start changing stuff, we can still refer to threejs/examples and docs. doesn't seem realistic atm to go into that with 3-4 ppl contributing.

I agree with having them done for v1 is unrealistic, setting the tooling up though 👌🏼
