### ISSUE TITLE
Identified error in bare import

### ISSUE THREAD

**Issue by Starcounter-Jack** [pmndrs/three-stdlib#140]
The file ```three-stdlib/modifiers/CurveModifier.js``` tries to do an import using the bare import specifier ```types/shared```. This will not be resolved correctly. Many hosts, ESM implementations and bundlers will attempt to look at the npm package ```types/shared```.

Most robust resolvers (such as typescript, esbuild, etc) will then fail instead of restoring to 'trial-and-error` methods like looking around for a match. There is no way to know the intention is ```./types/shared``` or ```/types/shared``` or if it should be triumphed by a matching entry in ```node_modules```. Package.json is of no help as it is not declared there.

The intention is to reference the package local directory, so the import specifier should be replaced with ```../types/shared```.
I recommend avoiding base imports unless they are declared as a dependency in package.json.

I've seen this error reported frequently by users of Drei and elsewhere. It has been closed, due to lack of investigation.

`import { TUniform } from 'types/shared'

**Comment by bjornstar** [comment]
This should be fixed by #142, thank you for the bug report!
