### ISSUE TITLE
[v2.9.1][typescript] I can't access to TextureNode

### ISSUE THREAD

**Issue by BenLune** [pmndrs/three-stdlib#148]
- `three` 0.139.2:
- `@types/three` 0.139.0:
- `three-stdlib` version : 2.9.1

### Problem description:

It seems that all classes in nodes folder are inaccessibles in a typescript project

### Suggested solution:

When I look at the Node.js file in the nodes folder of the thre
<img width="547" alt="Capture d’écran 2022-04-19 à 18 50 53" src="https://user-images.githubusercontent.com/5662714/164114123-787d53d6-2b17-4994-b87c-39d4b91f5ef1.png">
e-stdlib folder in node_modules, I find the TextureNode class imported from ./accessors folder, but when I look into the Nodes.d.ts files the TextureNode is exported from an ./inputs folder which doesn't seem to exist.

**Comment by CodyJasonBennett** [comment]
This should be fixed in `@types/three` 0.144 from https://github.com/three-types/three-ts-types/pull/240.
