### ISSUE TITLE
three-stdlib's Line2 is behind that of three.js/examples/jsm/lines

### ISSUE THREAD

**Issue by roman-kh** [pmndrs/three-stdlib#159]
### Describe the feature you'd like:
three.js Line2 classes have several important features like better raycasting, worldUnits coordinates, and so on.
It'll be nice that three-stdlib Line2 be reconciled with three.js version.

**Comment by CodyJasonBennett** [comment]
Should be fixed in [`v2.14.2`](https://github.com/pmndrs/three-stdlib/releases/tag/v2.14.2).
