### ISSUE TITLE
interface GLTF lack two attributes: nodes and materials

### ISSUE THREAD

**Issue by Gjb7598189** [pmndrs/three-stdlib#166]
interface GLTF lack two attributes: nodes and materials
![类型文件](https://user-images.githubusercontent.com/25116778/174752000-16584a49-728a-41b2-a86a-3483264156db.png)

**Comment by Gjb7598189** [comment]
who can help me?

**Comment by drcmda** [comment]
nodes & materials aren't part of the gltf loader output, they're added by useLoader/useGLTF. i asked on threejs GH once but they were against adding these two, so they are exclusive to the react+three eco system. things like gltfjsx automatically type them out.

**Comment by Gjb7598189** [comment]
thanks @drcmda for the help。
so, I can only solve this by extending the global ts type?

**Comment by CodyJasonBennett** [comment]
Should be fixed in Drei [`v9.25.3`](https://github.com/pmndrs/drei/releases/tag/v9.25.3).
