### ISSUE TITLE
Storybook setup?

### ISSUE THREAD

**Issue by mysterybear** [pmndrs/three-stdlib#169]
### Describe the feature you'd like:

The Storybook setup seems strange, why can't we write stories in R3F style? Feeling blocked on https://github.com/pmndrs/three-stdlib/pull/167 as it's not obvious how to add some interaction (click) handlers or HTML buttons with the current vanilla Three setup and no obvious access to the DOM

### Suggested implementation:

The Drei storybook setup is conducive to R3F style code, maybe can copy this?

**Comment by Carnageous** [comment]
I would argue that this is a good thing, even though I definitley get that it's a blocker. This package can and should be used without r3f, so writing the storybook with r3f could limit how examples can be used for none-r3f users.
Having a mix of both styles would also be not ideal, but maybe possible?

**Comment by mysterybear** [comment]
Okay fair enough, will close this then, didn't realise it was R3F/Three-agnostic
