### ISSUE TITLE
CCDIKHelper is not exported

### ISSUE THREAD

**Issue by sbiaudet** [pmndrs/three-stdlib#173]
- `three` 0.143.0:
- `three-stdlib` 2.13.0:

### Problem description:

export 'CCDIKHelper' (imported as 'CCDIKHelper') was not found in 'three-stdlib'

### Relevant code:

```js
import { CCDIKSolver, CCDIKHelper } from 'three-stdlib';
```

### Suggested solution:

Export CCDIKHelper in /animation/CCDIKSolver.js

**Comment by CodyJasonBennett** [comment]
Unless I misunderstand, I'm treating this as a feature request since there is nothing internally trying to import the helper. I have however refactored the CCDIKSoler module to export classes and tree-shake properly in #181.

**Comment by CodyJasonBennett** [comment]
Published in `2.16.0`.
