### ISSUE TITLE
Data3DTexture cannot be imported

### ISSUE THREAD

**Issue by kian00sh** [pmndrs/three-stdlib#175]
- `three` version: 0.135.0
- `@types/three` version: 0.130.2
- `three-stdlib` version: 2.14.1
- `ktx-parse` version: 0.4.5

### Problem description:

Code cannot be compiled after upgrading dependencies. Before running `yarn upgrade` this problem did not occur. `three-stdlib` was upgraded from 2.12.1 to 2.14.1.

### Relevant code:

```
Failed to compile.

./node_modules/three-stdlib/loaders/KTX2Loader.js
Attempted import error: 'Data3DTexture' is not exported from 'three'.
```

**Comment by drcmda** [comment]
could you update your threejs version? they have had breaking changes. three-stdlib is usually kept up to date.

**Comment by kian00sh** [comment]
@drcmda Upgrading `three` to 0.143.0 seems to resolve the issue. I had not realized there was a newer version of `three` that yarn did not install. Thanks for your help!
