### ISSUE TITLE
export 'ParametricGeometry' (imported as 'ParametricGeometry') was not found in 'three'

### ISSUE THREAD

**Issue by tombombadilom** [pmndrs/three-stdlib#178]
react 18.2.0
@react-three/fiber v8.6.2
@react-three/drei v9.25.3
three v0.144.0
three-stdlib v2.14.3

hi I have those 3 errors from three-stdlib 

`ERROR in ./node_modules/three-stdlib/geometries/ParametricGeometries.js 101:2-25

export 'ParametricGeometry' (imported as 'ParametricGeometry') was not found in 'three' (possible exports: ...)`

`ERROR in ./node_modules/three-stdlib/geometries/ParametricGeometries.js 161:2-25

export 'ParametricGeometry' (imported as 'ParametricGeometry') was not found in 'three' (possible exports: ....`

`ERROR in ./node_modules/three-stdlib/geometries/ParametricGeometries.js 180:2-25

export 'ParametricGeometry' (imported as 'ParametricGeometry') was not found in 'three' (possible exports: ...`

**Comment by Shtoner** [comment]
Same here was just trying to import orbitcontrols and got lost in error messages.

**Comment by tombombadilom** [comment]
just with this import, without rendering anything I get the error
```
import { Canvas, useFrame, useThree } from "@react-three/fiber";
import { Image, Scroll, ScrollControls, useScroll } from "@react-three/drei";
```

**Comment by DaanKorver** [comment]
Also facing the same issue.

**Comment by ridhof** [comment]
facing the same issue, with code below:

```
import * as Drei from "@react-three/drei";

export default () => {
  const { scene } = Drei.useGLTF("http://localhost:3000/monkey.glb");
  console.log(scene);

  return (
    <h1>Test</h1>
  );
};
```

error
```
No matching export in "node_modules/three/build/three.module.js" for import "ParametricGeometry"

    node_modules/three-stdlib/geometries/ParametricGeometries.js:1:18:
      1 │ import { Vector3, ParametricGeometry, BufferGeometry,...
        ╵                   ~~~~~~~~~~~~~~~~~~
```

package.json
```
"dependencies": {
    "@react-three/drei": "^9.25.3",
    "@react-three/fiber": "^8.6.2",
    "@types/three": "^0.144.0",
    "astro": "^1.1.5"
  },
  "devDependencies": {
    "@astrojs/react": "^1.1.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "typescript": "^4.8.2"
  }
```
