### ISSUE TITLE
SSR Compatible

### ISSUE THREAD

**Issue by RenaudRohlinger** [pmndrs/three-stdlib#18]
### Describe the feature you'd like:

It would be nice to make the three-stdlib server-side compatible.

- [ ] Wrap all usage of the "document" variable with a condition.

**Comment by joshuaellis** [comment]
IMO this is a v1 requirement no? How many files do you think there are? 🤔

**Comment by drcmda** [comment]
Let's also remove document if we can. Loaders für instance could all work just fine under node, the only reason they don't is that xhr request stuff. If they would take a promise then how something is loaded is up the client, and that would even work for react native.

**Comment by RenaudRohlinger** [comment]
@joshuaellis It should be around 20 files, not a big deal

**Comment by joshuaellis** [comment]
If you could list them people can help out if you're cool with that?

**Comment by joshuaellis** [comment]
Just an update, I haven't made my way to this yet, but there's a demo/ssr that also goes up to codesandbox, that can be used to test the SSR work 👍🏼 its a small nextjs project minimal deps
