### ISSUE TITLE
Circular Dependency Causes issues with Rollup if you have --failAfterWarnings flag on

### ISSUE THREAD

**Issue by TheEvilDev** [pmndrs/three-stdlib#191]
- `three` version:
- `@types/three` version:
- `three-stdlib` version:

### Problem description:

The issue is that there is a circular file dependency that causes issues for some bundlers, in my example rollup. If you turn on the `--failAfterWarnings` flag in the rollup config, it fails due to:

```
(!) Circular dependency
src/nodes/Nodes.js -> src/nodes/loaders/NodeLoader.js -> src/nodes/Nodes.js
```

This is even true if you just build this package and look at the output. While not critical, I don't believe this circular dependency was intended or necessary. 

### Relevant code:

```
(!) Circular dependency
src/nodes/Nodes.js -> src/nodes/loaders/NodeLoader.js -> src/nodes/Nodes.js
```

### Suggested solution:

Given the lack of test coverage in this project, I am also not confident enough to send a pull request to address this, but my initial thinking is to split the `Nodes.js` file separating out the nodeLib and `Nodes.fromType` into a helper, and keep `Nodes.js` purely for exporting reasons, but this is likely a breaking change in the API, unless we also export the `fromTypes` helper on the external interface, and consume it from the internal one everywhere else.

**Comment by matt-sparq** [comment]
This causes an error every time three-stdlib is imported when using the bun development server. It currently prevents us from using anything from `three-stdlib` or `@react-three/drei`.
