### ISSUE TITLE
Closure compiler errors with shadow-cljs using react-three/drei - Continued

### ISSUE THREAD

**Issue by ShakoFarhad** [pmndrs/three-stdlib#207]
### NPM dependancies:
    "@react-three/fiber": "8.9.1",
    "@react-three/drei": "9.45.1",
    "three-stdlib": "2.20.0",
    "three": "0.146.0",
    "react": "18.2.0",

### Problem description:
Related to #204 and #205 

I added the newest three-stdlib to my repo and tested again. Without the shadow-cljs config dependancy resolve, this issue is still there.

    Closure compilation failed with 1 errors
    --- node_modules/three-stdlib/index.cjs.js:2
    Illegal variable reference before declaration: t
    
Activating the shadow-cljs config dependancy resolve fix now shows reduced amount of errors compared to earlier, but still one remaining.

    Closure compilation failed with 1 errors
    --- node_modules/three-stdlib/helpers/LightProbeHelper.js:21
    cannot access this before calling super()

### Suggested solution:
I tried fixing it by making this change to the LightProbeHelper.js file.

```Javascript
import { Mesh, ShaderMaterial, SphereGeometry } from 'three';

class LightProbeHelper extends Mesh {
  constructor(lightProbe, size) {
    const material = new ShaderMaterial({
      type: 'LightProbeHelperMaterial',
      uniforms: {
        sh: {
          value: lightProbe.sh.coefficients
        },
        // by reference
        intensity: {
          value: lightProbe.intensity
        }
      },
      vertexShader: ['varying vec3 vNormal;', 'void main() {', '	vNormal = normalize( normalMatrix * normal );', '	gl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );', '}'].join('\n'),
      fragmentShader: ['#define RECIPROCAL_PI 0.318309886', 'vec3 inverseTransformDirection( in vec3 normal, in mat4 matrix ) {', '	// matrix is assumed to be orthogonal', '	return normalize( ( vec4( normal, 0.0 ) * matrix ).xyz );', '}', '// source: https://graphics.stanford.edu/papers/envmap/envmap.pdf', 'vec3 shGetIrradianceAt( in vec3 normal, in vec3 shCoefficients[ 9 ] ) {', '	// normal is assumed to have unit length', '	float x = normal.x, y = normal.y, z = normal.z;', '	// band 0', '	vec3 result = shCoefficients[ 0 ] * 0.886227;', '	// band 1', '	result += shCoefficients[ 1 ] * 2.0 * 0.511664 * y;', '	result += shCoefficients[ 2 ] * 2.0 * 0.511664 * z;', '	result += shCoefficients[ 3 ] * 2.0 * 0.511664 * x;', '	// band 2', '	result += shCoefficients[ 4 ] * 2.0 * 0.429043 * x * y;', '	result += shCoefficients[ 5 ] * 2.0 * 0.429043 * y * z;', '	result += shCoefficients[ 6 ] * ( 0.743125 * z * z - 0.247708 );', '	result += shCoefficients[ 7 ] * 2.0 * 0.429043 * x * z;', '	result += shCoefficients[ 8 ] * 0.429043 * ( x * x - y * y );', '	return result;', '}', 'uniform vec3 sh[ 9 ]; // sh coefficients', 'uniform float intensity; // light probe intensity', 'varying vec3 vNormal;', 'void main() {', '	vec3 normal = normalize( vNormal );', '	vec3 worldNormal = inverseTransformDirection( normal, viewMatrix );', '	vec3 irradiance = shGetIrradianceAt( worldNormal, sh );', '	vec3 outgoingLight = RECIPROCAL_PI * irradiance * intensity;', '	gl_FragColor = linearToOutputTexel( vec4( outgoingLight, 1.0 ) );', '}'].join('\n')
    });
    const geometry = new SphereGeometry(1, 32, 16);
    super(geometry, material);
    this.lightProbe = lightProbe;
    this.size = size;
    this.type = 'LightProbeHelper';
    this.onBeforeRender();
  }

  dispose() {
    this.geometry.dispose();
    this.material.dispose();
  }

  onBeforeRender() {
    this.position.copy(this.lightProbe.position);
    this.scale.set(1, 1, 1).multiplyScalar(this.size);
    this.material.uniforms.intensity.value = this.lightProbe.intensity;
  }

}

export { LightProbeHelper };
```

With this I now get these warnings.
    
      Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
    ------ WARNING #1 -  -----------------------------------------------------------
     Resource: node_modules/three-stdlib/postprocessing/UnrealBloomPass.js:235:20
     String continuations are not recommended. See https://google.github.io/styleguide/jsguide.html#features-strings-no-line-continuations
    --------------------------------------------------------------------------------
    ------ WARNING #2 -  -----------------------------------------------------------
     Resource: node_modules/three-stdlib/postprocessing/UnrealBloomPass.js:240:22
     String continuations are not recommended. See https://google.github.io/styleguide/jsguide.html#features-strings-no-line-continuations
    --------------------------------------------------------------------------------
    ------ WARNING #3 -  -----------------------------------------------------------
     Resource: node_modules/three-stdlib/postprocessing/UnrealBloomPass.js:304:20
     String continuations are not recommended. See https://google.github.io/styleguide/jsguide.html#features-strings-no-line-continuations
    --------------------------------------------------------------------------------
    ------ WARNING #4 -  -----------------------------------------------------------
     Resource: node_modules/three-stdlib/postprocessing/UnrealBloomPass.js:309:22
     String continuations are not recommended. See https://google.github.io/styleguide/jsguide.html#features-strings-no-line-continuations
    --------------------------------------------------------------------------------

I am not sure if I should just comment on the closed issue or create a new one so I did both. Please tell me if one is preferred over the other. Sorry for the inconvenience I may have caused!

**Comment by CodyJasonBennett** [comment]
I've cleaned up withstanding bug-severity issues in #208 as a follow-up to this and the earlier issue, but those warnings are Google's internal engineering opinions for what should be authored code -- it is not of anyone's interest to resolve them upstream.
