### ISSUE TITLE
make controls programmatically controllable

### ISSUE THREAD

**Issue by drcmda** [pmndrs/three-stdlib#22]
probably one of the most requested features for controls, for instance orbit:

orbit.pan(x, y)
orbit.zoom(level)
orbit.rotate(delta, phi)

currently controls are sealed and can only be controlled by pointer input, which also creates a problem bc once you have controls, nothing else is allowed to move the camera bc it would cancel movement out.

**Comment by CodyJasonBennett** [comment]
This is something I've been trying to tinker with, but I haven't figured out how to make play nice with damping.

**Comment by drcmda** [comment]
at work we had this once, damping and all. i remember that i simply copied the code thats in the generic rotate/pan/zoom functions and made it generic. it was using the same damping settings.

**Comment by CodyJasonBennett** [comment]
I see that there was already [a PR that you commented on](https://github.com/mrdoob/three.js/pull/9005) that *somewhat* did this.

I suspected that we were to rip out the math from the update method, but is that still the case? I ask this because the following logic still has a dependency on the update method, and I'm not sure if that's the intention.

```js
this.pan = function ( deltaX, deltaY ) {
  pan( deltaX, deltaY );
  scope.update();
};
```

**Comment by drcmda** [comment]
here are the two i made years ago: https://gist.github.com/drcmda/6be8a22b824ce29922509c0483f0f1b3

the controls are outdated for sure and as i wrote in that issue, im not a mathematician - there may be better ways. looking at it it's mostly happening in _automate and i didn't understand the concept of lerping back then, it could be easier

**Comment by haywirez** [comment]
This is now merged via #65 I think

**Comment by agcty** [comment]
why was this closed? I'm somewhat new to threejs, but how does #65 implement programmatic panning for example? is there a way to do this with just the azimuthal and polar angles?

**Comment by drcmda** [comment]
panning is not implemented just polar and azimuth. you can add it though as another pr, it would make sense to have it.
