### ISSUE TITLE
TrackballControls.target is private, no way of setting...

### ISSUE THREAD

**Issue by xinaesthete** [pmndrs/three-stdlib#222]
I'm not sure how one's supposed to programmatically point at a particular coordinate. I was just trying to update a project which had been using `TrackballControls` from three examples, changed to this version and hit a TS error... for now, I've worked around it by casting as `any` to avoid TS picking up on the problem.

**Comment by CodyJasonBennett** [comment]
This is available with https://github.com/pmndrs/three-stdlib/releases/tag/v2.23.0.
