### ISSUE TITLE
Mouse event(s) not stopped nor forwarded in TransformControls cause misplaced click

### ISSUE THREAD

**Issue by akiross** [pmndrs/three-stdlib#224]
Hello,
I'm using `TransformControls` via `drei`, but I think the problem originates in this library, and I'm unsure if this is known fact considered Ok, or it is a bug to resolve.

The problem is that, after dragging the `TransformControls` via gizmo/plane, when the mouse button is release, it might trigger a click event over another object under the mouse.

This is visible also in the drei `TransformControls` example: https://codesandbox.io/s/btsbj

Here a gif of what's happening

![](https://user-images.githubusercontent.com/884092/219703823-9807332f-7997-4efa-9ea0-e324ce53b69d.gif)

I think the problem is that the event is not stopped nor forwarded to the event handler, so there is no way to stop it and will trigger a click.

Personally I'd like to have control over the event so I think it should be forwarded, but maybe you know about workarounds or other solutions (?)

**Comment by drcmda** [comment]
imo it's not a bug in drei.

these things are hard to fix with 3rd party controls. transform doesn't call stopPropagation, nor should it, but also doesn't allow you to control the event phase. even if it did stop, it would be a race condition unless you make sure transform gets the event first.

i would use drei/pivotcontrols. it uses events on meshes, and it calls stop. it wouldn't happen there.

**Comment by akiross** [comment]
Yes, I realized it wouldn't make sense to stop the event bubbling in there, but maybe it made sense to pass the event to the callbacks.

Using the PivotControls probably makes more sense; I'll close the issue and try with that one.

Thank you!
