### ISSUE TITLE
The KTX2Loader doesn't support CompressedArrayTexture

### ISSUE THREAD

**Issue by pietrovismara** [pmndrs/three-stdlib#229]
### Describe the feature you'd like:

The `KTX2Loader` doesn't support yet array textures and isn't able to return a `CompressedArrayTexture`.

[three-stdlib version](https://github.com/pmndrs/three-stdlib/blob/main/src/loaders/KTX2Loader.js#L213)
[three addons version](https://github.com/mrdoob/three.js/blob/master/examples/jsm/loaders/KTX2Loader.js#L261)

### Suggested implementation:

Porting the feature seems just a matter of adjusting that line but I'm not familiar enough with the codebase to be sure of it. Happy to open a PR if someone can confirm the scope of the change.

**Comment by CodyJasonBennett** [comment]
My colleague added this in https://github.com/mrdoob/three.js/pull/24745, but we're unable to use this from three.js itself since it's not available in older versions. If three.js doesn't use `instanceof` or constructor checks, we could polyfill or shim it here though.

**Comment by CodyJasonBennett** [comment]
This is implemented with https://github.com/pmndrs/three-stdlib/releases/tag/v2.22.0.

**Comment by pietrovismara** [comment]
Thanks for the quick fix!
