### ISSUE TITLE
`loadAsync` missing from loaders

### ISSUE THREAD

**Issue by musjj** [pmndrs/three-stdlib#237]
- `three` version: 0.152.2
- `@types/three` version: 0.152.0
- `three-stdlib` version: 2.21.11

### Problem description:

`loadAsync` is missing from all loaders

### Relevant code:

```js
import { FontLoader } from "three-stdlib";
const fontLoader = new FontLoader();
fontLoader.loadAsync(font)
           ^
           Property 'loadAsync' does not exist on type 'FontLoader'. [2339]
```

### Suggested solution:

`@types/three` already have `loadAsync` typed for all of its loaders:
https://github.com/three-types/three-ts-types/tree/master/types/three/examples/jsm/loaders
Maybe we can adopt them for this repo?

**Comment by CodyJasonBennett** [comment]
IIRC they recently removed the `loadAsync` signature from the `Loader` types, so we'll have to add it ourselves. Can make a type helper to prevent breakage like this.

**Comment by musjj** [comment]
Thank you for the fix! But it seems that the return value of the function isn't typed correctly.

For example, with `@types/three`:

```js
import { FontLoader } from "three/examples/jsm/loaders/FontLoader.js";
const fontLoader = new FontLoader();
fontLoader.loadAsync(fontFile).then((font) => {
    console.log(font);
                ^
                (parameter) font: Font 
});
```

But with `three-stdlib`:

```js
import { FontLoader } from "three-stdlib";
const fontLoader = new FontLoader();
fontLoader.loadAsync(fontFile).then((font) => {
    console.log(font);
                ^
                (parameter) font: any  
});
```

`@types/three` types the return value correctly for each loader:

https://github.com/three-types/three-ts-types/blob/b2ff16404b9d4d290e2aac3a02a5e1af5ba5db3e/types/three/examples/jsm/loaders/FontLoader.d.ts#L12

But `three-stdlib` resorts to a generic `Any` type:

https://github.com/pmndrs/three-stdlib/blob/35f014c20e54d69fa505345394f4bfe97508dce1/src/types/Loader.ts#L5

**Comment by CodyJasonBennett** [comment]
I think we'll have to add all the member signatures individually like they did. Don't see how we can hide the issue.

**Comment by musjj** [comment]
Thank you, it's working perfectly!
