### ISSUE TITLE
Module not found: Error: Can't resolve '@webgpu/glslang/dist/web-devel/glslang' in '/opt/build/repo/node_modules/three-stdlib/dist/renderers/webgpu' Did you mean 'glslang.js'?

### ISSUE THREAD

**Issue by sbhaya** [pmndrs/three-stdlib#244]
- `three` version: ^0.152.2
- `@types/three` version:^0.152.1
- `three-stdlib` version:^2.22.8

### Problem description:

I have been able to solve the solution locally by updating the import statement in 'WebGPURenderer.js' and 'WebGPURenderer.mjs', but when I am deploying to netlify, the same problem reappears, and I am unable to solve it. 

### Suggested solution:

const glslang = await import("@webgpu/glslang/dist/web-devel/glslang.js");

**Comment by CodyJasonBennett** [comment]
Sorry, this slipped through. I have #241 which should resolve surrounding issues, pending integration testing.
