### ISSUE TITLE
Missing ``matcap-porcelain-white`` texture

### ISSUE THREAD

**Issue by dmoore04** [pmndrs/three-stdlib#246]
`<!--`

* Please fill out this template with all the relevant information so we can
  understand what's going on and fix the issue. We appreciate bugs filed and PRs
  submitted!

* You can get the installed version of an NPM package by running `npm ls <insert package name>` in your terminal.

-->

- `three` version:
- `@types/three` version:
- `three-stdlib` version:

### Relevant code:

```js
let your = (code, tell) => `the ${story}`
```

**Comment by CodyJasonBennett** [comment]
I believe this is fixed with https://github.com/pmndrs/three-stdlib/releases/tag/v2.22.10 which removes side-effects from offscreen which references `matcap-porcelain-white`.
