### ISSUE TITLE
OrbitControls.zoomToCursor missing

### ISSUE THREAD

**Issue by alessiocancian** [pmndrs/three-stdlib#285]
- `three` version: 0.156.1
- `@types/three` version: 0.156.0
- `three-stdlib` version: 2.51.1

### Problem description:

Three.js documentation mentions a `zoomToCursor` prop for OrbitControls but I can't use it with @react-three/drei because three-stdlib's OrbitControls doesn't support it.
https://threejs.org/docs/?q=zoomToCursor#examples/en/controls/OrbitControls.zoomToCursor

### Suggested solution:

Update OrbitControls on three-stdlib.

**Comment by CodyJasonBennett** [comment]
https://github.com/mrdoob/three.js/pull/26165, https://github.com/mrdoob/three.js/pull/26549
