### ISSUE TITLE
Setup Codesandbox CI & Semantic Release

### ISSUE THREAD

**Issue by gsimone** [pmndrs/three-stdlib#3]

**Comment by joshuaellis** [comment]
Semantic release might be nice – hmu if you want that added.

Also running a build in an action will help detect Type errors too 👍🏼

**Comment by gsimone** [comment]
+1 on semantic

**Comment by joshuaellis** [comment]
Added `semantic-release-action`

**Comment by joshuaellis** [comment]
Added the codesandbox CI & we're using local sandbox env inside `demo`, I've made one for SSR in the interest of #18
