### ISSUE TITLE
`ReferenceError: STATE$1 is not defined` in `>=2.25.1`

### ISSUE THREAD

**Issue by dozortsev** [pmndrs/three-stdlib#301]
- `three-stdlib` version: >=2.25.1

### Problem description:

After `2.25.1` `dist/index.cjs.js` contains alias `STATE$1` for [`STATE` enum](https://github.com/pmndrs/three-stdlib/blob/main/src/controls/experimental/CameraControls.ts#L18).

This causes a runtime/client-side error in Next.js (in my case v12) applications when run the app via `next build & next start`, the error:

```
ReferenceError: STATE$1 is not defined
```

<details>
  <summary>Screenshot</summary>
  
<img width="1531" alt="Screen Shot 2023-10-04 at 11 22 49 AM copy" src="https://github.com/pmndrs/three-stdlib/assets/4015628/265b9ec1-6422-41eb-bcc6-fb433391c5b7">
</details>

---

`dist/index.cjs.js` in `2.25.0`, no alias for `STATE`

<img width="1371" alt="Screen Shot 2023-10-04 at 3 23 31 PM" src="https://github.com/pmndrs/three-stdlib/assets/4015628/64e5daed-9280-4c14-85c0-f90467686817">

`dist/index.cjs.js` after `2.25.1`, `STATE` is an alias for `STATE$1`

<img width="1381" alt="Screen Shot 2023-10-04 at 3 28 23 PM" src="https://github.com/pmndrs/three-stdlib/assets/4015628/fb79a959-5c32-48aa-a023-088141ef15a3">

### Relevant code:

...

### Suggested solution:

Was `STATE` enum were actually meant to be exported from [`CameraControls.ts`](https://github.com/pmndrs/three-stdlib/blob/main/src/controls/experimental/CameraControls.ts#L18)?

**Comment by CodyJasonBennett** [comment]
`STATE` is exported from `CameraControls`, what you're seeing is code generation from TypeScript's enums. I'd first try disabling any transpilation that Next is doing that may split or transpile `three-stdlib`. The package is well formed, so I'm afraid there's nothing immediately actionable unless we can link this upstream.

**Comment by dozortsev** [comment]
Hey @CodyJasonBennett, thanks for taking a look!

My package isn't specified in `transpileModules` of `next.config.js`

when I install my package in some Next.js and add `three-stdlib` in list of `resolutions` of `package.json` with `2.25.0` version

```
  "resolutions": {
    "three-stdlib": "2.25.0"
  }
```

things work, I mean don't get `STATE$1 is not defined` error

**Comment by CodyJasonBennett** [comment]
Which version of Next v12 are you using exactly? I'd give #302 a try with the following:

```json
{
  "resolutions": {
    "three-stdlib": "https://pkg.csb.dev/pmndrs/three-stdlib/commit/4160b199/three-stdlib"
  }
}
```

**Comment by dozortsev** [comment]
This works! 👏
