### ISSUE TITLE
STL Exporter Only Compatible with Skinned Meshes

### ISSUE THREAD

**Issue by hunter-digital** [pmndrs/three-stdlib#320]
### Problem description:

In the most recent version of the STL exporter, it's typed to only export instances of SkinnedMeshes. Why is this?

It led to a lot of confusion, as I had considered this library as a preferable alternative and essentially identical to using the /examples directory in three.js itself. I found that the three.js exporter doesn't have this issue.

### Relevant code:

```js
if (object instanceof SkinnedMesh) {
        if (index !== null) {
          // indexed geometry

          for (let j = 0; j < index.count; j += 3) {
            const a = index.getX(j + 0)
            const b = index.getX(j + 1)
            const c = index.getX(j + 2)

            this.writeFace(a, b, c, positionAttribute, object)
          }
        } else {
          // non-indexed geometry

          for (let j = 0; j < positionAttribute.count; j += 3) {
            const a = j + 0
            const b = j + 1
            const c = j + 2

            this.writeFace(a, b, c, positionAttribute, object)
          }
        }
```

### Suggested solution:

When I removed the instanceof conditional above, the exporter worked again.

**Comment by CodyJasonBennett** [comment]
> It led to a lot of confusion, as I had considered this library as a preferable alternative and essentially identical to using the /examples directory in three.js itself.

That is a weird thing to say on any open-source project. I'd simply say this is a bug. I personally maintain these modules both in three and here, but this looks to have regressed when this repository was created and some modules were converted to TypeScript. Most now are maintained in JS and .d.ts so we can upstream work with `@types/three`. `instanceof SkinnedMesh` was likely a crude attempt at making the TypeScript compiler happy in type narrowing.
