### ISSUE TITLE
Line color not working

### ISSUE THREAD

**Issue by Methuselah96** [pmndrs/three-stdlib#337]
- `three` version: any
- `@types/three` version: any
- `three-stdlib` version: 2.29.0 and 2.29.1

### Problem description:

Setting the color of a `Line` seems to no longer work with drei, presumably caused by https://github.com/pmndrs/three-stdlib/pull/335 either directly or indirectly.

### Relevant code:

```js
import { Vector3 } from 'three'
import { Canvas } from '@react-three/fiber'
import { Line, OrbitControls } from '@react-three/drei'
import { GeometryUtils } from 'three-stdlib'

const points = GeometryUtils.hilbert3D(new Vector3(0), 5).map((p) => [p.x, p.y, p.z])

function BasicLine() {
  return <Line points={points} color="red" lineWidth={3} />
}

export default function App() {
  return (
    <Canvas>
      <ambientLight intensity={Math.PI / 2} />
      <spotLight position={[10, 10, 10]} angle={0.15} penumbra={1} decay={0} intensity={Math.PI} />
      <pointLight position={[-10, -10, -10]} decay={0} intensity={Math.PI} />
      <BasicLine />
      <OrbitControls />
    </Canvas>
  )
}
```

[CodeSandbox](https://codesandbox.io/p/sandbox/icy-bash-l2k36q)

### Suggested solution:

?

**Comment by CodyJasonBennett** [comment]
Likely multiplied by `0` (or initial values) when vertex colors aren't specified.
