### ISSUE TITLE
What is the relationship between this lib with drei

### ISSUE THREAD

**Issue by fnick851** [pmndrs/three-stdlib#34]
### What is your question:

Currently to use `drei` in next.js I need to do: 

```js
const withTM = require("next-transpile-modules")([
  "three/examples/jsm/lines/LineGeometry",
  "@react-three/drei",
])
```

Would this library work with drei somehow and eliminate the needs for "next-transpile-modules"?

Thanks.

**Comment by joshuaellis** [comment]
Hi @fnick851

Give `@react-three/drei@beta` a go, it requires `three-stdlib` as a peer dep! It's our v4 beta that will be released alongside v6 of `react-three-fiber` & `react-three-test-renderer`.

If there are any bugs please open up new issues here, or `drei` depending on what they're related too!
