### ISSUE TITLE
useGLTF with KTX2Loader 

### ISSUE THREAD

**Issue by KallkaGo** [pmndrs/three-stdlib#354]
i use gltfpack to compression model and Texture ，so i use `useGLTF` to load it
this is my code :
![image](https://github.com/pmndrs/three-stdlib/assets/82202033/98fd3100-e5f0-4a82-af37-d206f6d66ef5)
but i got an error
![image](https://github.com/pmndrs/three-stdlib/assets/82202033/2ce23bbc-e934-4a96-8ec3-25cbd9e68b1d)
Interestingly using the KTX2Loader from `three/example` it works fine.
Is my usage wrong? Or is there something wrong with the KTX2Loader of three-stdlib?

version：
 @react-three/drei: "9.105.3",
  @react-three/fiber: "^8.16.2",
  three: "^0.161.0",
  three-stdlib: "2.29.6",

**Comment by CodyJasonBennett** [comment]
This looks like a bug, nothing wrong on your part. I'll take a closer look.

**Comment by jereloh** [comment]
> i use gltfpack to compression model and Texture ，so i use `useGLTF` to load it this is my code : ![image](https://private-user-images.githubusercontent.com/82202033/323275285-98fd3100-e5f0-4a82-af37-d206f6d66ef5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MTQwMjEsIm5iZiI6MTcxMzQxMzcyMSwicGF0aCI6Ii84MjIwMjAzMy8zMjMyNzUyODUtOThmZDMxMDAtZTVmMC00YTgyLWFmMzctZDIwNmY2ZDY2ZWY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA0MTUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0NzFlMzAwZDY0YTQ4YmRlY2MzM2QyYmYyZjEyNDk5MTY0NjlkZjY5YThlMjZmZTRlOWUzNmRhMzBlYzMxNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A1xn9hIyRX1uyMOJmeJ3e66XDLN1DMNMzO9J2nEeDI8) but i got an error ![image](https://private-user-images.githubusercontent.com/82202033/323275778-2ce23bbc-e934-4a96-8ec3-25cbd9e68b1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MTQwMjEsIm5iZiI6MTcxMzQxMzcyMSwicGF0aCI6Ii84MjIwMjAzMy8zMjMyNzU3NzgtMmNlMjNiYmMtZTkzNC00YTk2LThlYzMtMjVjYmQ5ZTY4YjFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA0MTUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZDYyODM1MDEzMWQyMjY1ZjkxMjVmOTJjZTM0OWU3ZGUyNTI0NzljZjAxNjg2NzAwN2U2MzFmYTZkNWI1MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NBi6mLlpqlGibKjJRu1x7_Ii_FgAmqZ-c92_CrvBdPk) Interestingly using the KTX2Loader from `three/example` it works fine. Is my usage wrong? Or is there something wrong with the KTX2Loader of three-stdlib?
> 
> version： @react-three/drei: "9.105.3", @react-three/fiber: "^8.16.2", three: "^0.161.0", three-stdlib: "2.29.6",

Having same issue using:

"@react-three/drei": "^9.105.4",
"@react-three/fiber": "^8.16.2",
"three": "^0.163.0",
"three-stdlib": "^2.29.6",

**Comment by CodyJasonBennett** [comment]
Fixed with #374.
