### ISSUE TITLE
Consider adding `@babel/runtime` as a peer dependency

### ISSUE THREAD

**Issue by smhutch** [pmndrs/three-stdlib#38]
### Describe the feature you'd like:

Consider adding `@babel/runtime` as a peer dependency. After installing the lib for the first time, and calling `new OrbitControls`, I received an error flagging that this dependency was required.

**Comment by joshuaellis** [comment]
Thanks for the input @smhutch, could you screenshot the error please?

It might be better if we use it in our deps. I'll have to look into `@babel/runtime` now.

**Comment by joshuaellis** [comment]
Ah yes, looking at the docs for one of our plugins, you should install it as a dep: https://babeljs.io/docs/en/babel-plugin-transform-runtime#installation

**Comment by joshuaellis** [comment]
resolved by #39

**Comment by smhutch** [comment]
Thanks @joshuaellis :)
