### ISSUE TITLE
Line2 RuntimeError due to LineSegmentGeometry

### ISSUE THREAD

**Issue by disambiguator** [pmndrs/three-stdlib#41]
- `three` version: 0.126.0
- `three-stdlib` version: 1.0.1

### Problem description:

Line2 causes runtime error:
```js
TypeError: _LineSegmentsGeometry_js__WEBPACK_IMPORTED_MODULE_1__.LineSegmentsGeometry.prototype.setPositions is undefined
```

This is because the constructor tries to instantiate a LineGeometry, which tries to call parent method `setPositions` [here](https://github.com/pmndrs/three-stdlib/blob/main/src/lines/LineGeometry.ts#L28).

LineSegmentsGeometry does not end up having this property because we use arrow functions to define setPositions in LineGeometry [here](https://github.com/pmndrs/three-stdlib/blob/main/src/lines/LineSegmentsGeometry.ts#L59). Arrow functions in classes compile to properties on the instance of a class, instead of on the prototype itself.

### Suggested solution:

Move all methods in LineSegmentsGeometry to use function syntax. This will solve this initial bug, but part of me thinks this issue will crop up again and there's a more sophisticated approach to avoiding it in the future.

**Comment by joshuaellis** [comment]
resolved by #42
