### ISSUE TITLE
Line Material is broken

### ISSUE THREAD

**Issue by joshuaellis** [pmndrs/three-stdlib#43]
- `three` version: 126
- `three-stdlib` version: current

### Problem description:

Line Material is badly broken

### Relevant code:

Check the storybook on alpha

**Comment by disambiguator** [comment]
I noticed this on drei@beta as well. Not really sure what's going on regarding color as read-only, given that there are public getters and setters.

**Comment by joshuaellis** [comment]
> I noticed this on drei@beta as well. Not really sure what's going on regarding color as read-only, given that there are public getters and setters.

That bug I believe is *either* the order of calling `setValues` before `Object.defineProperties` OR using the property `enumerable` however, its a bit more broken than that, tbh I might just recopy the original from `three` and go from there. If you're interested this could be something you could look at?

**Comment by disambiguator** [comment]
@joshuaellis i can later this week for sure!

**Comment by joshuaellis** [comment]
fixed via pmndrs/three-stdlib@174ab6c
