### ISSUE TITLE
TransformControls partially broken

### ISSUE THREAD

**Issue by stephent** [pmndrs/three-stdlib#51]
- `three` version: 0.127.0
- `three-stdlib` version:  ^1.1.4

### Problem description:

TransformControls events do not fire and control does not respond to changes in the mode property. Originally reported in https://github.com/pmndrs/drei/issues/355

- Storybook implementation appears that it is intended to disable OrbitControls when the TransformControls is dragged, but this is not working (tested in Safari 14 + Chrome 89). As the transform is dragged, both it and the camera move
- Changing the knobs for TransformControlsLockSt does not make any change in the appearance or function of the TransformControl, e.g. changing from translation to rotation leaves TransformControl in 'translate' mode.

### Relevant code:

Try the stories here:

https://drei.pmnd.rs/?path=/story/controls-transformcontrols--transform-controls-lock-st

This drop in JS replacement that references `three/examples/jsm/controls/TransformControls` instead of `three-stdlib` appears to work as expected.

```js
import * as React from 'react'
import { useThree } from '@react-three/fiber'
import { TransformControls as TransformControlsImpl } from 'three/examples/jsm/controls/TransformControls'
import pick from 'lodash.pick'
import omit from 'lodash.omit'

export const PatchedTransformControls = React.forwardRef(({ children, ...props }, ref) => {
  const transformOnlyPropNames = [
    'enabled',
    'axis',
    'mode',
    'translationSnap',
    'rotationSnap',
    'scaleSnap',
    'space',
    'size',
    'dragging',
    'showX',
    'showY',
    'showZ',
  ]

  const { camera, ...rest } = props
  const transformProps = pick(rest, transformOnlyPropNames)
  const objectProps = omit(rest, transformOnlyPropNames)

  const gl = useThree(({ gl }) => gl)
  const defaultCamera = useThree(({ camera }) => camera)
  const invalidate = useThree(({ invalidate }) => invalidate)

  const explCamera = camera || defaultCamera

  const [controls] = React.useState(() => new TransformControlsImpl(explCamera, gl.domElement))

  const group = React.useRef()
  React.useLayoutEffect(() => void controls?.attach(group.current), [children, controls])

  React.useEffect(() => {
    controls?.addEventListener?.('change', invalidate)
    return () => controls?.removeEventListener?.('change', invalidate)
  }, [controls, invalidate])

  return controls ? (
    <>
      <primitive ref={ref} dispose={undefined} object={controls} {...transformProps} />
      <group ref={group} {...objectProps}>
        {children}
      </group>
    </>
  ) : null
})
```

### Suggested solution:

No idea of the root cause as yet, but will update if I discover more.

**Comment by gsimone** [comment]
This is caused by the properties being renamed here 
https://github.com/pmndrs/three-stdlib/commit/295ca10f4463d45511005eaa510a8b924967c528#diff-b58ed75b1a1aff9ca07e396dd7f9a888843da850f959112cc830db2c3b3d590b

Now the called events would be, for example, `_dragging-changed` instead of `dragging-changed`, breaking the stories. 

This is not ideal, but I'm not sure why they were renamed @joshuaellis

**Comment by joshuaellis** [comment]
is `dragging-changed` an event prop? My *assumption* when changing it was these were all private props, maybe i'm wrong?  I don't really get why this would break everything, do you mind explaining @gsimone so I understand for the future 😓

**Comment by gsimone** [comment]
The component generate change events that are based on the property's name, so 

`_dragging is set => _dragging-changed event is dispatched`

You could modify the dispatcher code if you want, to remove the `_`, that's also an option but not sure if it's worth the additional brain cost 👯

**Comment by joshuaellis** [comment]
Probably easier to revert the prefix no?

**Comment by joshuaellis** [comment]
Hm i've reverted that change and it doesn't *seem* to have solved the issue.

**Comment by drcmda** [comment]
i think the issue is fixed, i cant reproduce it any longer with the beta. we could push a patch version imo.
