### ISSUE TITLE
OrbitControls saveState differ from Three's

### ISSUE THREAD

**Issue by partynikko** [pmndrs/three-stdlib#54]
- `three` version: r127
- `three-stdlib` version: v1.2.4

### Problem description:

There is an inconsistency regarding the OrbitControls method `saveState` and how it behaves. In Three, the `camera.zoom` is saved while saving the state of the controls, regardless if the camera is a perspective one or orthographic:
https://github.com/mrdoob/three.js/blob/3d59a07b32394c1a0d57c8558775d0ba3a54d7da/examples/jsm/controls/OrbitControls.js#L123-L129

 In this library this is not the case any longer (it used to be but was changed in [938045a](https://github.com/pmndrs/three-stdlib/commit/938045a3b77ccd9edb04064f2e0798bf721acbf8#diff-8a02d71e67deb0d9a2045fb5260a6a8298f3625ad8280ebb4f766aed9ca76707L94-R122)). Now it is only saved for perspective cameras.

Due to the camera zoom of orthographic cameras no longer being saved, resetting the OrbitControls with the `reset` method will not properly reset the camera to previous state.

### Relevant code:

https://github.com/pmndrs/three-stdlib/blob/cc079be1d2bb5f619202341a2fa53a4cb006056c/src/controls/OrbitControls.ts#L112-L116

### Suggested solution:

If this was not done intentionally due to some weird behavior I would suggest to just revert that specific line, making it possible to properly save the state of orthographic cameras. 

If it was done intentionally, it would be nice with a comment explaining why 👍

**Comment by joshuaellis** [comment]
I'd probably just revert it. Maybe someone thought there was no zoom on OrthoGraphic Camera?

**Comment by partynikko** [comment]
> I'd probably just revert it. Maybe someone thought there was no zoom on OrthoGraphic Camera?

Yeah, could be that it was mixed up with the OrbitControls properties `maxZoom/minZoom` which only applies to orthographic cameras, and `maxDistance/minDistance` for perspective cameras. Both camera types do have zoom though.
