### ISSUE TITLE
React-Three-Fiber break's with Three 0.128.0

### ISSUE THREAD

**Issue by webdesign2be** [pmndrs/three-stdlib#55]
Hi,

I tried to load a GLTF and OBJ File into a Scene with the actual versions of three and RTF.
Unfortunately RTF break's with the newest version of ThreeJS (0.128.0)

Easy to reproduce with 
- https://codesandbox.io/s/objloader-51zks?from-embed
- https://codesandbox.io/s/gltfjsx-vbnbf?from-embed

Errors: 
- `TypeError: Class constructor CompressedTextureLoader cannot be invoked without 'new'`
- `TypeError: Class constructor Loader cannot be invoked without 'new'`

Just change Three version to 0.128.0 and the error will appear in console.

Kind regards

**Comment by joshuaellis** [comment]
To summarise for whoever wants to fix this, `threejs` managed to convert everything to `classes` so things like `loaders` need to be called with `new`.

**Comment by webdesign2be** [comment]
Does that include the GLTFtoJSX converter?

**Comment by joshuaellis** [comment]
This library needs to be updated, whatever depends on it will break when you use it with three@128. If you use GLTFtoJSX with r127 you'll be fine.

**Comment by drcmda** [comment]
this pr should fix it
