### ISSUE TITLE
Canvas events trigger only when OrbitControls disabled

### ISSUE THREAD

**Issue by xiaopohaier** [pmndrs/three-stdlib#61]
I want to listen events on Canvas，so I try to bind events on wrapper element.
However the wrapper event will trigger only when I set  OrbitControls disabled, I guess is a bug and need help, thx

demo as follow
https://codesandbox.io/s/suspicious-sun-q895j?file=/src/App.js

**Comment by drcmda** [comment]
this is not a bug, thats just how threejs orbit controls work. i think they call preventdefault/stoppropagation. perhaps something can be done in three-stdlib.

**Comment by CodyJasonBennett** [comment]
Is this still an issue? IIRC R3F uses a different container for event tracking now.
