### ISSUE TITLE
WebXR, update XRHandMesh

### ISSUE THREAD

**Issue by AdaRoseCannon** [pmndrs/three-stdlib#63]
ThreeJS has updated the XRHand Mesh to use the official model from immersive-web/webxr-input-profiles rather than the inbuilt Oculus one, in addition there have been some changes in the way hand tracking works which may be out of date.

https://github.com/mrdoob/three.js/blob/dev/examples/jsm/webxr/XRHandMeshModel.js

**Comment by CodyJasonBennett** [comment]
Sorry for the late response. Changes were synchronized and upstreamed awhile ago, but things should now be up-to-date.
