### ISSUE TITLE
CharsetEncoder of CommonJS error on Importing to Codepen

### ISSUE THREAD

**Issue by srcnalt** [pmndrs/three-stdlib#81]
- `three` version: ^0.128.0
- `three-stdlib` version: ^2.4.0

### Problem description:

Importing the package in a Codepen project outputs the error below and breaks the project. Tried from different CDN urls however got the same result. I suspect this is an issue with the package however wanted to note here since a project depending on this package can't be run on the platform.
```
Uncaught TypeError: Cannot destructure property 'CharsetEncoder' of '__commonjs_module0' as it is null.
    at three-stdlib.js:5
```

### Relevant code:

```jsx
import * as threeStdlib from "https://cdn.skypack.dev/three-stdlib@2.4.0";

const { useState } = React;

const App = () => (
  <h2>Hello World!</h2>
);

ReactDOM.render(<App />, document.getElementById('app'));
```

**Comment by vorth** [comment]
I'm seeing the same issue, using Snowpack in my dev environment.  In my case, it is a transitive impact from this import:

```
import { PerspectiveCamera } from 'https://cdn.skypack.dev/@react-three/drei'
```

**Comment by drcmda** [comment]
to me it looks like the issue is with skypack: https://cdn.skypack.dev/-/three-stdlib@v2.4.0-VYwL2mAg7OLmwnegfVgd/dist=es2020,mode=imports/optimized/three-stdlib.js

```jsx
import __commonjs_module0 from "/-/mmd-parser@v1.0.4-cQrs3jZFV6EDoYehjWaL/dist=es2020,mode=imports/optimized/mmd-parser.js";
const {CharsetEncoder} = __commonjs_module0;
const {Parser} = __commonjs_module0;
```

imo that should be `import * as __commonjs_module0 from ...`

**Comment by drcmda** [comment]
ps. you can reach individual esm files: https://unpkg.com/browse/@react-three/drei@7.3.1/core/PerspectiveCamera.js, that would be `@react-three/core/PerspectiveCamera`

**Comment by vorth** [comment]
> ps. you can reach individual esm files: https://unpkg.com/browse/@react-three/drei@7.3.1/core/PerspectiveCamera.js, that would be `@react-three/core/PerspectiveCamera`

Thank you, but unfortunately it doesn't help, since PerspectiveCamera.js has some module specifiers that don't work without a toolchain (or import maps):
```
import _extends from '@babel/runtime/helpers/esm/extends';
import * as React from 'react';
import { useThree } from '@react-three/fiber';
import mergeRefs from 'react-merge-refs';
```

**Comment by drcmda** [comment]
could you move the issue to skypack? if they have a look i think that would be best.
