### ISSUE TITLE
No more mouseDown event in TransformControls

### ISSUE THREAD

**Issue by lescurej** [pmndrs/three-stdlib#85]
- `three` version: 0.132.2
- `three-stdlib` version: 2.4.0

### Problem description:

mouseDown event is no more triggered in TransformControls, probably since f59f1e2ca818dfed9b9322432463ed8f51eda04c

### Relevant code:

https://github.com/pmndrs/three-stdlib/blob/f59f1e2ca818dfed9b9322432463ed8f51eda04c/src/controls/TransformControls.ts#L283-L286

### Suggested solution:

```js
this.mouseDownEvent.type = this._mode 
````
should be
```js
this.mouseDownEvent.mode = this._mode 
````

Otherwise the dispatchEvent will trigger a 'translate'|'scale'|'rotate' event instead of mouseDown event

As shown on the three.js current master branch:
https://github.com/mrdoob/three.js/blob/e62b253081438c030d6af1ee3c3346a89124f277/examples/jsm/controls/TransformControls.js#L278-L282

**Comment by drcmda** [comment]
its also broken in jsm? could you make the change as a pr?

**Comment by lescurej** [comment]
jsm looks good :
https://github.com/mrdoob/three.js/blob/e62b253081438c030d6af1ee3c3346a89124f277/examples/jsm/controls/TransformControls.js#L278-L282

Added a pull request above
