### ISSUE TITLE
Failed to Compile due to Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by iamabigartist** [pmndrs/three-stdlib#87]
- `three` version: ^0.132.2
- `three-stdlib` version: ^2.4.1

### Problem description:

When I set up a new project and run it. The compiler gives this error:

./node_modules/three-stdlib/exporters/ColladaExporter.js 127:20
Module parse failed: Unexpected token (127:20)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
  |
  |       return res;
  \>     }).join('\n')) ?? '';
  |   } // Convert an image into a png format for saving
  |

### Suggested solution:
i tried to install esm later but it dosen't work.

**Comment by sampsale** [comment]
I have the same problem, if you find a solution could you inform me as well? :)

**Comment by joshuaellis** [comment]
Please provide a small code example of the issue, e.g a code sandbox

**Comment by akdjr** [comment]
I've had a similar issue with older versions of babel and the ?? (null coalescing) operator - perhaps that's where problem is?

**Comment by mbodge** [comment]
Same issue, not sure where the dependency is coming from i have

`"@react-three/drei": "6.1.2",
		"@react-three/fiber": "7.0.1",
		"@react-three/postprocessing": "^2.0.5",`

and i went to build my nextjs app today and it gave me the exact error above

**Comment by joshuaellis** [comment]
The dep is used in drei, for us to investigate, it'd be helpful to have a minimal reproduction of the bug.

**Comment by joshuaellis** [comment]
Oh i've just thought, has anyone tried adding this plugin to their `babel` config? – https://babeljs.io/docs/en/babel-plugin-proposal-nullish-coalescing-operator

**Comment by drcmda** [comment]
i think we must do it. i had the same trouble with r3f: https://github.com/pmndrs/react-three-fiber/blob/master/babel.config.js

**Comment by joshuaellis** [comment]
Hm I'm not sure i entirely agree, where do you draw the line in what you polyfill and transpile? 

Optional chaining is in the same position yet we don't transpile that currently in particular libraries.

**Comment by drcmda** [comment]
i had problems in all libraries that had it: r3f, gltfjsx and some others. i think the feature is not ripe to be in dist. and the babel transform is very small. i think it's too much to ask people to change their build systems for something like that, and then there's node and ssr, where they likely have no choice.

with this config i practically never encounter issues or complaints:

```json
[
      '@babel/preset-env',
      {
        include: [
          '@babel/plugin-proposal-optional-chaining',
          '@babel/plugin-proposal-nullish-coalescing-operator',
          '@babel/plugin-proposal-numeric-separator',
          '@babel/plugin-proposal-logical-assignment-operators',
        ],
        bugfixes: true,
        loose: true,
        modules: false,
        targets: '> 1%, not dead, not ie 11, not op_mini all',
      },
    ],
```

**Comment by iamabigartist** [comment]
> Please provide a small code example of the issue, e.g a code sandbox

Actually, drei and three-stdlib work fine in the code sandbox at this time. And I just transferred my entire project to the sandbox online yesterday.

Without any code, it seems the compiler won't check these libraries so no error. So here is my small code example:
```
import {Canvas} from "@react-three/fiber";
import {Billboard, Plane} from "@react-three/drei";

export function TestBillBoard() {
    return (
        <Canvas>
            <Billboard follow={true} position={[0, 0, 0]}>
                <Plane args={[3, 2]} material-color="red"/>
            </Billboard>
        </Canvas>);
}
```
  
Then use this code in index.tsx:
```
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import reportWebVitals from './reportWebVitals';
import {TestBillBoard} from "./ThreeTest";

ReactDOM.render(
    <div><TestBillBoard/></div>,
    document.getElementById('root')
);

reportWebVitals();
```

On the other hand, **this is my project setup process**:
1. In Webstorm, New Project-> React Project->Select generate typescript project -> Create
![屏幕截图 2021-09-24 212121](https://user-images.githubusercontent.com/53459343/134681402-d72e322e-c7ac-4fa7-9911-fdfbe96ff143.png)
(It's the create react app process provided by JetBrains).
2. Then wait for the project to be set up. 
3. Then in the terminal, run 'yarn add three @types/three' -> 'yarn add @react-three/fiber @react-three/drei' -> 'yarn install'
4. Then insert the code. 
5. Then use npm run start to run the project, then the compiler gave the compile error.

**Comment by iamabigartist** [comment]
> I have the same problem, if you find a solution could you inform me as well? :)

Sure

**Comment by iamabigartist** [comment]
Here is a close relative stackoverflow problem: ["You may need an additional loader to handle the result of these loaders" (React Native)](https://stackoverflow.com/questions/66054352/you-may-need-an-additional-loader-to-handle-the-result-of-these-loaders-react)

**Comment by iamabigartist** [comment]
The CodeSandbox works perfectly for now, maybe they have a different version of babel?
![image](https://user-images.githubusercontent.com/53459343/134686422-5db752ad-14a5-4e63-b6ae-6b8f40a3cd79.png)

**Comment by delacannon** [comment]
I also got the error in a simple CRA app. I fixed the issue by adding `@babel/plugin-proposal-nullish-coalescing-operator` on the craco config file.

```
// craco.config.js
module.exports = {
  babel: {
    plugins: ["@babel/plugin-proposal-nullish-coalescing-operator"],
  },
};
```

**Comment by neftaly** [comment]
Also getting this on a new CRA app. I'd set the threshold for pollyfilling/transpiling as "does this work on stock CRA?"

**Comment by drcmda** [comment]
> Also getting this on a new CRA app. I'd set the threshold for pollyfilling/transpiling as "does this work on stock CRA?"

i think that makes sense. i'll make the changes
