### ISSUE TITLE
Consider adding font loader

### ISSUE THREAD

**Issue by johno** [pmndrs/three-stdlib#91]
As a result of https://github.com/mrdoob/three.js/pull/22560 the font loader was removed from Three's core and lives in the example dir. Would you folks be interested in adding it as part of the stdlib?

## Related

- https://github.com/mrdoob/three.js/pull/22536

**Comment by joshuaellis** [comment]
Absolutely, feel free to make a PR ☺️

**Comment by johno** [comment]
Great, will open one up tomorrow. Thanks!
