### ISSUE TITLE
Two finger Zoom Incorrect Trackball Contorls with orthographic camera

### ISSUE THREAD

**Issue by prmdandy** [pmndrs/three-stdlib#93]
https://github.com/pmndrs/three-stdlib/blob/5618b2a3eb0b7896b0ec56372ec57b93d298a018/src/controls/TrackballControls.ts#L170

jsm/contorls/Trackball controls has this line a /= instead of *=

**Comment by drcmda** [comment]
could you make the change?

**Comment by CodyJasonBennett** [comment]
Fixed with https://github.com/pmndrs/three-stdlib/pull/94.
